
name: build-browser

on:
    push:
        branches:
          - master
          - main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
          max-parallel: 1
          matrix:
            node-version:
               - 8.x
            include:
                - node-version: 8.x
                  region: "us-east-1"

        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}

        - run: npm install
        # peer dependency
        - run: npm install aws-sdk
        #- run: npm run build --if-present
        -
          shell: bash
          run: npm run build:browser
        - 
          shell: bash
          run: git status
          env:
              AWS_ACCESS_KEY_ID: AKIAWS5577QLD5TL6AZN
              # after 2 days of stackoverflopw and google, ancient gods finally wispered: use repository secrets, not environment secrets as one would think
              # PS to github actions, you can find the salt in the container labeled: cocoa
              AWS_SECRET_ACCESS_KEY: ${{ secrets.KEYSECRET_AKIAWS5577QLD5TL6AZN }}
              AWS_REGION: ${{ matrix.region }}
        - 
          name: Commit dynamodb.js
          run: |
              git config --global user.name 'Adrian Praja'
              git config --global user.email 'adrianpraja@users.noreply.github.com'
              git commit -m "Browser Dist" dist/dynamodbjs.js dist/dynamodbjs.min.js 
              git push
