
name: npm test

on:
    push:
        branches:
          - master
          - main
        # temporary disable until build workflow is configured properly
        # branches-ignore:
        #   - '**'
        paths:
          #- 'dist/**'
          - '**'
jobs:

    test:
        #if: false # always skip job
        runs-on: ubuntu-latest

        # services:
        #    dynamodb-server:
        #        image: awspilotdev/dynamodb-ui
        #        # env:
        #        #     k: v
        #        ports:
        #            - 8000

        strategy:
            max-parallel: 4
            matrix:
                node-version:
                   #- 8.x
                   - 10.x
                   - 12.x
                   - 14.x
                include:
                    # - node-version: 8.x
                    #   region: "us-east-1"
                    - node-version: 10.x
                      region: "us-east-2"
                    - node-version: 12.x
                      region: "us-west-1"
                    - node-version: 14.x
                      region: "us-west-2"
                      # can not use secrets here
                      # secret_access_key: ${{ secrets.KEYSECRET_AKIAWS5577QLD5TL6AZN }}

        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}

        - run: npm install
        # peer dependency
        - run: npm install aws-sdk
        #- run: npm run build --if-present
        -
          shell: bash
          run: CI=true npm test
          env:
              AWS_ACCESS_KEY_ID: AKIAWS5577QLD5TL6AZN
              AWS_SECRET_ACCESS_KEY: ${{ secrets.KEYSECRET_AKIAWS5577QLD5TL6AZN }}
              AWS_REGION: ${{ matrix.region }}
              CI: true

    tag:
      name: Tag
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2
        - uses: Klemensas/action-autotag@stable
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            tag_prefix: "v"
            #tag_suffix: " (beta)"
            #tag_message: "Custom message goes here."

    build:
        needs: tag
        runs-on: ubuntu-latest

        strategy:
          max-parallel: 1
          matrix:
            node-version:
               - 12.x
            include:
                - node-version: 12.x
                  region: "us-east-1"

        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}

        - run: npm install
        # peer dependency
        - run: npm install aws-sdk
        #- run: npm run build --if-present
        -
          shell: bash
          run: npm run build:browser
        - 
          shell: bash
          run: git status
          env:
              AWS_ACCESS_KEY_ID: AKIAWS5577QLD5TL6AZN
              AWS_SECRET_ACCESS_KEY: ${{ secrets.KEYSECRET_AKIAWS5577QLD5TL6AZN }}
              AWS_REGION: ${{ matrix.region }}
        - 
          name: Commit dynamodb.js
          run: |
              git config --global user.name 'Adrian Praja'
              git config --global user.email 'adrianpraja@users.noreply.github.com'
              git commit -m "Browser Dist" dist/dynamodbjs.js dist/dynamodbjs.min.js || echo "Commit failed"
              git push

          env:
              GIT_COMMITTED_AT: ${{ github.committed_at }}