
name: Regression Testing

on:
  push:
    branches:
      - master
      - main

jobs:

   services:
       dynamodb-server:
           image: awspilotdev/dynamodb-ui
           # env:
           #     k: v
           ports:
               - 8000

   build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
           # - 8.x
           - 10.x
           # - 12.x
           # - 14.x
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    #- run: npm ci
    #- run: npm run build --if-present
    #- run: npm install -g mocha@5.2.0
    #- run: npm install -g async@2.6.3

    - run: npm install
    # peer dependency
    - run: npm install aws-sdk
    - run: npm test
