
name: Regression Testing

on:
  push:
    branches:
      - master
      - main

jobs:



   test:

    runs-on: ubuntu-latest

    # services:
    #    dynamodb-server:
    #        image: awspilotdev/dynamodb-ui
    #        # env:
    #        #     k: v
    #        ports:
    #            - 8000

    strategy:
      max-parallel: 1
      matrix:
        node-version:
           - 8.x
           - 10.x
           # - 12.x
           # - 14.x
        include:
            - node-version: 8.x
              region: "eu-central-1"
            - node-version: 10.x
              region: "eu-central-1"

    steps:
    - uses: actions/checkout@v2
    # to check
    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1

    # try debug env
    - uses: hmarr/debug-action

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    # peer dependency
    - run: npm install aws-sdk
    -
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ matrix.region }}
      run: npm test
