
name: Regression Testing

on:
  push:
    branches:
      - master
      - main

jobs:



   build:

    runs-on: ubuntu-latest

    # services:
    #    dynamodb-server:
    #        image: awspilotdev/dynamodb-ui
    #        # env:
    #        #     k: v
    #        ports:
    #            - 8000

    strategy:
      matrix:
        node-version:
           - 8.x
           - 10.x
           # - 12.x
           # - 14.x
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    # peer dependency
    - run: npm install aws-sdk
    - run: npm test
